#ifndef	__LTIN_PORTTABLE_H__
#define	__LTIN_PORTTABLE_H__

/***** インクルード *****/
#include "ltin.h"

/***** テーブル *****/
S_LT_PORTINFO T_LT_SENSORPORT_TABLE[E_RSI_SENSOR_PORT_NUM] =
{
	{ E_LT_PARTS_TOUCH_SENSOR	, E_RSI_SENSOR_PORT_1		, E_RSI_SENSOR_TYPE_TOUCH	},
	{ E_LT_PARTS_NONE			, E_RSI_SENSOR_PORT_2		, E_RSI_SENSOR_TYPE_NONE	},
	{ E_LT_PARTS_COLOR_SENSOR	, E_RSI_SENSOR_PORT_3		, E_RSI_SENSOR_TYPE_COLOR	},
	{ E_LT_PARTS_GYRO_SENSOR	, E_RSI_SENSOR_PORT_4		, E_RSI_SENSOR_TYPE_GYRO	},
};

S_LT_PORTINFO T_LT_MOTORPORT_TABLE[E_RSI_MOTOR_PORT_NUM] =
{
	{ E_LT_PARTS_TAIL_MOTOR		, E_RSI_MOTOR_PORT_A		, E_RSI_MOTOR_TYPE_MEDIUM	},
	{ E_LT_PARTS_RIGHT_MOTOR	, E_RSI_MOTOR_PORT_B		, E_RSI_MOTOR_TYPE_LARGE	},
	{ E_LT_PARTS_LEFT_MOTOR		, E_RSI_MOTOR_PORT_C		, E_RSI_MOTOR_TYPE_LARGE	},
	{ E_LT_PARTS_NONE			, E_RSI_MOTOR_PORT_D		, E_RSI_MOTOR_TYPE_NONE		},
};

#endif	/* __LTIN_PORTTABLE_H__ */
